config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tasks do
    member do
      get "complete"
    end
    collection do
      get "search"
      get "generate"
      post "generate", to: "tasks#create_generated"
    end
  end

  resource :profile, only: [ :show, :edit, :update ] do
    collection do
      get "view/:uuid", action: :view, as: :view
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :view ]

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(update_params)

    redirect_to profile_path, notice: "Updated!"
  end

  def view
    @user = User.find_by!(uuid: params[:uuid], published: true)
  rescue ActiveRecord::RecordNotFound => e
    redirect_to root_path(message: "Profile not found!")
  end

  private

  def update_params
    params.require(:user).permit(:portfolio_url, :published)
  end
end

app/views/profiles/edit.html.erb
<h1 class="mb-4">Update Personal Info</h1>

<%= form_with(model: @user, url: profile_path, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :portfolio_url, class: 'form-label' %>
    <%= form.text_field :portfolio_url, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :published, class: 'form-label' %>
    <div class="form-check">
      <%= form.checkbox :published, class: 'form-check-input' %>
      <%= form.label :published, class: 'form-check-label' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.submit 'Update', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/profiles/show.html.erb
<div class="d-flex justify-content-between align-items-center mb-4">
  <h1>Profile</h1>
  <%= link_to 'Edit Profile', edit_profile_path, class: 'btn btn-primary' %>
</div>

<div class="mb-3">
  <p><strong>Email:</strong> <%= @user.email %></p>
</div>

<div class="mb-3">
  <p><strong>Portfolio Url:</strong> <%= @user.portfolio_url %></p>
</div>

<% if @user.published? %>
  <div class="mb-3">
    <p><strong>Sharable Url:</strong> <%= view_profile_url(@user.uuid) %></p>
  </div>
<% end %>

<div class="mb-3">
  <p><strong>Status:</strong> <%= @user.published ? 'Public' : 'Private' %></p>
</div>

<%= link_to 'Back', root_path, class: 'btn btn-secondary' %>

app/views/profiles/view.html.erb
<h2 class="mb-4">User Portfolio</h2>

<div class="mb-3">
<p><strong>Email:</strong> <%= @user.email %></p>
</div>

<div class="mb-3">
<p><strong>Portfolio Url:</strong> <%= link_to @user.portfolio_url, @user.portfolio_url, class: 'btn btn-link' %></p>
</div>

<%= link_to 'Back', root_path, class: 'btn btn-secondary' %>